Feature branch
Christabelle143/Christy-budget pull request #1
Opened 2023-01-07 22:08 UTC by Christabelle143

# In this project i completed the following tasks;

### Project requirements

#### Interactions
- Splash screen
  - A simple page with the name of your app (yes, you need to choose one), and links to the sign up and log in pages.

- Sign up and log in pages
  - The user should be able to register in the app with full name, email and password (all mandatory).
  - The user can log into the app using email and password.
  - If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).

- Home page (catagories page)
  - When the user logs in, they are presented with the categories page.
  - For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
  - When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
  - There is a button "add a new category" at the bottom that brings the user to the page to create a new category.

- Transactions page
  - For a given category, the list of transactions is presented, ordered by the most recent.
  - At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
  - There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
  - When the user clicks on the "Back" button (<), the user navigates to the home page.

- "Add a new category" page
  - The user fills out a form to create a new category, indicating their name and icon (both mandatory).
  - The user click (or taps) the "Save" button to create the new category, and is taken to the home page on success.
  - When the user clicks on the "Back" button (<), the user navigates to the home page.

- "Add a new transaction" page
  - The user fills out a form to create a new transaction with:
    - name (mandatory)
    - amount (mandatory)
    - categories (mandatory at least one)
  - The user click (or taps) the "Save" button to create the new transation, and is taken to the transactions page for that category.
  - When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.

#### Testing requirements
- Create unit and integration tests for all the most important components of your RoR application.

2023-01-07 22:14 UTC, Christabelle143 commented
Hey, 
This is for the reviewer. Thanks for taking time to review my project. I lack one thing on the project which is the live link. I have been working on it for like 3 hours now to no avail using render. Tried using Heroku but can't proceed since I don't have a credit card. Will work on it further but due to the deadline I have to submit my project without it for now. I will definitely add it when I succeed. Hope you will be compassionate with me for this  week reviewer.
Thanks in advance.
Here is a screenshots of my different trials on render
![render](https://user-images.githubusercontent.com/98928638/211172205-e9726727-969c-4c2e-acae-b34a26380f29.PNG)

2023-01-07 22:46 UTC, rloterh reviewed
Hi Christabelle, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

I get the error below in attempt to start your application. Kindly ensure to update the online version of your code if your local version of code is working as intended:

![image](https://user-images.githubusercontent.com/12745474/211173092-b37498f9-ed94-4008-8bfa-2059e3c8117c.png)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-07 22:59 UTC, Christabelle143 commented
just fixed the issue thanks.

2023-01-08 01:04 UTC, andersonlebon requested changes
## Hi @Christabelle143 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)

## Suggested changes
_Check the comments under the review._

- [ ] Nice work on recording a looming video :clap: :clap:  however, one of the video presentation requirements says that your video should contain a highlight about a piece of the code that you find interesting or you are proud of making. Kindly work on this so that your project gets strong documentation.

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-01-08 01:04 UTC, andersonlebon commented on .stylelintrc.json
>    },
- [ ] I have Tested your project locally and it's really nice, nice job on using the active storage to attach to the transaction a logo or avatar(jpg, png...), However, your project still needs to follow the styling requirements of the project
![image](https://user-images.githubusercontent.com/65068771/211175700-ca6abfab-813a-45d1-8e58-c642ec26f05d.png) ![image](https://user-images.githubusercontent.com/65068771/211175715-6b5cd73b-ec80-469d-b7c0-4f917ba6b5e3.png) ![image](https://user-images.githubusercontent.com/65068771/211175723-1581c4d9-683b-4c12-9752-ca95bf4655ca.png) ![image](https://user-images.githubusercontent.com/65068771/211175753-6b1a13bc-883d-4110-b86b-be31b446452e.png) ![image](https://user-images.githubusercontent.com/65068771/211175914-fde8ce93-ae13-44f3-8490-cd5d454473e8.png) 

The images above show all the Design requirements you should follow:
![image](https://user-images.githubusercontent.com/65068771/211176025-fed68c67-c16f-48be-93b8-23722cee6f0c.png)

2023-01-09 12:43 UTC, Lameck1 approved these changes
Hi, @Christabelle143,

**_This is a manual review._**

Tasks for this project have been successfully implemented 💯.
You understood the assignment and have done a good job 👍🏼.

All the best with the next project.

You are free to merge this branch :shipit:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

2023-01-11 09:54 UTC, merged